### ISSUE TITLE
Add Scrum Bot to Discord

### ISSUE THREAD

**Issue by NicholasNagy** [Fruity-Loops/ALTA#10]
Add a discord bot that would ask the team to answer the 3 essential questions of every scrum meeting on a daily basis.

The purpose is to get everyone's progress as often as possible in addition to the team-based scrum meetings.

**Comment by daphneaugier** [comment]
@Neeham told me about the patreon fo the Reminder-Bot for Discord and we got the monthly subscription for that in order to do our Daily scrum meetings.
