### ISSUE TITLE
User should log in with E-mail address

### ISSUE THREAD

**Issue by daphneaugier** [Fruity-Loops/ALTA#118]
### Details
**Summary** 
The current method to log into ALTA is by inputting a valid username and password. Since the creation of a username burdens the user to remember a unique name, the system should use the user's email address and password to perform the login functionality.

**Reproduction Steps:**

1. The user visits the ALTA landing page.

**Expected Results:**
The page requests the user's email address and password to be able to log into the system.
 

**Actual Results:**
The page requests the user's username and password to be able to log into the system. 

### Tracking

**Severity:** Medium
**Priority:** High
**Status:** Fixed

**Comment by RobertBeaudenon** [comment]
It is not a problem of labeling, this is how it was implemented at first with the username. Also it should not be considered as a BUG because it was the implementation. If we want to have email now instead of username we will have to do this migration in the backend then in the frontend.
