### ISSUE TITLE
AT-1.1: System administrator creates a system administrator account

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#129]
### User Story: ALTA-1.1 (#12)
As a system administrator, I want to be able to create a user account for other system administrators so that I can give users access to the ALTA platform.

### Acceptance Criteria
Given that the user is logged in as a system administrator and selects the _Manage Members_ side menu option,

1. The user should be presented with a table displaying other system administrators and a _Create_ button. 

2. The user selects the _Create_ button to display an empty form for the user to input the new user’s information.

3. Once the form is complete, the user submits the data by clicking the _Save_ button. The user is then redirected back to the table to validate the creation of the user.

**Comment by ajaykaushik17** [comment]
System Admin functionality of adding other system admin - ACCEPTED.
