### ISSUE TITLE
AT-1.2: System administrator modifies their account information

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#130]
### User Story: ALTA-1.2 (#43)
As a system administrator, I want to be able to modify my account information so that I can correct outdated data.

### Acceptance Criteria
Given that the user is logged in as a system administrator and selects the _Settings_ side menu option, 

1. The user should be presented with a form containing their previously supplied user information. 

2. The user selects the _Edit_ button to allow the fields to accept input.

3. Once the information is modified, the user selects the _Save_ button to store the updated data.

**Comment by ajaykaushik17** [comment]
System Admin Account Modification Functionality - Accepted
