### ISSUE TITLE
AT-1.3A: System administrator adds an organization

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#133]
### User Story: ALTA-1.3A (#71)
As a system administrator, I want to be able to add a new organization to ALTA so that I can build my clientele. 

### Acceptance Criteria
Given that the user is logged in as a system administrator,

1. The user should be redirected to the _Manage Organizations_ page which displays a table containing all organizations subscribed to ALTA.
2. The user selects the  _Add_ button to redirect to the _Organization Creation_ page.
3. The user enters the organization's name in the input field.
4. The user submits the new organization by selecting the _Save_ button.

**Comment by ajaykaushik17** [comment]
•	need to be able to include the organization's location upon creation and edit
•	instead of deleting an organization, change status to disabled or inactive

Status - Pending

**Comment by ajaykaushik17** [comment]
ACCEPTED
