### ISSUE TITLE
AT-1.4: System administrator create organization's employee's accounts

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#134]
### User Story: ALTA-1.4 (#33)
As a system administrator, I want to be able to create my client’s employee’s user account so that I can grant their employee access to ALTA.

### Acceptance Criteria
Given that the user is logged in as a system administrator and is viewing the _Manage Organizations_ page,

1. The user is able to select an organization by clicking on its respective row in the presented table. 

2. The user selects the _Employees_ side menu option.

3. The user is presented with a table displaying the affiliated employee user accounts and a _Create_ button. 

4. The user selects the _Create_ button to display an empty form for the user to input the new user’s information.

5. Once the form is complete, the user submits the data by clicking the _Save_ button. The user is then redirected back to the table to validate the creation of the user.

**Comment by ajaykaushik17** [comment]
Accepted - but in the table displaying an organization's employee's, display the user's role
Also Add Employee's location to map audit assignment (Specially for Stock keepers)
