### ISSUE TITLE
AT-1.5: System administrator modifies an organization's employee's account information

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#135]
### User Story: ALTA-1.5 (#39)
As a system administrator, I want to be able to modify a client’s employee’s user account so that I can reflect any changes requested to their account information.

### Acceptance Criteria
Given that the user is logged in as a system administrator,

1. The user selects an organization from the _Manage Organizations_ page.
2. The user selects the _Employees_ side menu option.
3. The user is presented with a table containing an overview of the affiliated employee user accounts' information.
4. The user selects the _Settings_ button (grey dot) at the end of the respective employee's row.
5. The user is presented with a form containing the employee's account information and selects the _Edit_ button.
6. Once the information is modified, the user selects the _Save_ button to store the updated data. The form is then refreshed to display the updated information.

**Comment by ajaykaushik17** [comment]
need to remove the option to change an employee's role to system admin
also, remove the option to change their password
Consider employee's location aspect for audit assignment 
Status - Pending

**Comment by ajaykaushik17** [comment]
ACCEPTED
