### ISSUE TITLE
AT-1.6: System administrator modifies an organization's employee's account status

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#136]
### User Story: ALTA-1.6 (#44)
As a system administrator, I want to be able to modify the status of a user account so that I can update their permissions.

### Acceptance Criteria
Given that the user is logged in as a system administrator and has selected an organization from the _Manage Organizations_ page,

1. The user selects the _Employees_ side menu option to present a table containing the affiliated employee user accounts' information.

4. The user selects the _grey dot_ button at the end of the respective employee's row to present the form containing the employee's account information.

5. The user selects the _Edit_ button to allow the fields to accept input. The user is able to alter the employee account's status to "active" or "disabled". 

6. Once the information is modified, the user selects the _Save_ button to store the altered status. The form is then refreshed to display the updated information.

**Comment by ajaykaushik17** [comment]
Accepted
