### ISSUE TITLE
AT-2.1: Inventory manager creates an inventory manager account

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#137]
### User Story: ALTA-2.1 (#42)
As an inventory manager, I want to be able to create a user account for another inventory manager so that I can provide access to initiate audits.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to their affiliated organization's _Dashboard_ page.

2. The user selects the _Employees_ side menu option and is presented with a table displaying the organization's employee accounts as well as a _Create_ button. 

2. The user selects the _Create_ button to display an empty form for the user to input the new user’s information.

3. Once the form is complete, the user submits the data by clicking the _Save_ button. The user is then redirected back to the table to validate the creation of the user.

**Comment by ajaykaushik17** [comment]
Accepted - but when creating a stock-keeper, disable the option to set a password
