### ISSUE TITLE
Inventory manager is redirected to Dashboard upon refresh

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#139]
### Details
**Summary** 
When a user is logged in as an Inventory Manager and is viewing any page other than _Dashboard_, the system will redirect them to Dashboard on refresh.

**Reproduction Steps:**

1. The user logs into the system as an Inventory Manager.
2. I select any option other than _Dashboard_ from the side menu options.
3. I refresh the browser window.

**Expected Results:**
The user will remain on the selected page once the refresh process is complete.
 

**Actual Results:**
The user is redirected back to the Dashboard page once the refresh process is complete.

### Tracking

**Severity:** Major
**Priority:** High
**Status:** New

**Comment by daphneaugier** [comment]
Bug report well explained. Starting working on that today! Seems that this could help me : https://github.com/angular/angular-cli/pull/3952
