### ISSUE TITLE
Refactoring Review

### ISSUE THREAD

**Issue by NicholasNagy** [Fruity-Loops/ALTA#171]
Look through code to look for areas to be refactored and define tasks for them.

This includes doing the following:
- Looking through the refactoring catalogue and attempting to find various types of refactorings that we can use on our app
- Look through the code to find areas where refactoring may be needed

Some potential ideas:
- Roles are hardcoded everywhere, we should have a central place for them
- Routes also have multiple places where they are hardcoded.
- We have multiple ways for storing global state: local storage and behaviours. We should stick to one way that is more reusable and requires less API calls, more looking into is required.

**Comment by makchamp** [comment]
Look to refactor django tests to use common test users instead of recreating the users in every test. 
A suggestion would be to read the users fromrecreating the users in every test a fixture (users.json)
@Averynder will look into this

**Comment by NicholasNagy** [comment]
> Look to refactor django tests to use common test users instead of recreating the users in every test.
> A suggestion would be to read the users from a fixture (like `users.json`)
> @Averynder will look into this

Okay, I will create an issue for him to assign him to this task
