### ISSUE TITLE
AT-1.3B: System administrator modifies an organization

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#188]
### User Story: ALTA-1.3B (#189)
As a system administrator, I want to be able to modify an organization’s data so that I can assist a customer if needed.

### Acceptance Criteria
Given that the user is logged in as a system administrator,

1. The user should be redirected to the _Manage Organizations_ page which displays a table containing all organizations subscribed to ALTA.
2. The user selects the _Settings_ button (grey dot) at the end of the respective organization's row in the table.
3. The user is presented with a form containing the organization's previously supplied information and selects the _Edit_ button.
4. The user submits the updated form by selecting the _Save_ button. The form is then refreshed to display the updated information.

**Comment by ajaykaushik17** [comment]
ACCEPTED
