### ISSUE TITLE
AT-1.3C: System administrator disables an organization's account

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#190]
### User Story: ALTA-1.3C (#191)
As a system administrator, I want to be able to disable an organization’s affiliated accounts so that I can restrict access to ALTA.

### Acceptance Criteria
Given that the user is logged in as a system administrator,

1. The user should be redirected to the _Manage Organizations_ page which displays a table containing all organizations subscribed to ALTA.
2. The user selects the _Settings_ button (grey dot) at the end of the respective organization's row in the table.
3. The user clicks on the _Status_ drop-down menu and selects the _Disabled_ option.
4. The user selects the _Save_ button.
5. The user enters the organization's name into the popup input field to validate the deactivation and selects the _Confirm_ button. The form is then refreshed to display the updated information.

**Comment by ajaykaushik17** [comment]
ACCEPTED
