### ISSUE TITLE
AT-2.3: Access organization's inventory data through ALTA

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#215]
### User Story: ALTA-2.3 (#46)
As an inventory manager, I want to be able to access the inventory data of the company’s ERP system through ALTA so that I can view potential items to audit.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Inventory Items_ side menu option.
3. The user is presented with a table containing the organization's inventory items collected from the data dump.

**Comment by ajaykaushik17** [comment]
This part is very well done. (ACCEPTED)
