### ISSUE TITLE
AT-2.4: Schedule automatic inventory data updates

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#216]
### User Story: ALTA-2.4 (#47)
As an inventory manager, I want to be able to schedule automatic inventory data updates at specified intervals so that I can view the latest version of the company’s ERP system’s data.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Organization Settings_ side menu option.
3. The user is presented with a form containing the FTP file location and the extract repetition rate.
4. The user selects the _Edit_ button.
5. The user inputs the designated location of the inventory data and sets the extract rate.
6. The user selects the _Save_ button. The form is then refreshed to display the updated information.

**Comment by ajaykaushik17** [comment]
Great feature for inventory managers. Need to make sure that scheduled audits are displayed to inventory manager on dashboard or designated area. (PENDING)

**Comment by ajaykaushik17** [comment]
Accepted.
