### ISSUE TITLE
AT-2.5: Search for an inventory item

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#217]
### User Story: ALTA-2.5 (#48)
As an inventory manager, I want to be able to search for an inventory item through ALTA so that I can include it in a potential audit.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Inventory Items_ side menu option.
3. The user is presented with a table containing the organization's inventory items collected from the data dump.
4. The user may search for an item in 2 ways:

    a. The user clicks on the search bar:
      1. The user inputs valid inventory criteria in the search bar.
      2. The user selects the _magnifying glass_ button to initiate the search.
      3. The inventory table updates to display the related data to the search.
     \
    b. The user selects the _Advanced Search_ button:
      1. The user is presented with a form of potential search fields.
      2. The user inputs valid inventory criteria in one or several fields.
      3. The user selects the _magnifying glass_ button to initiate the search.
      4. The inventory table updates to display the related data to the search.

**Comment by ajaykaushik17** [comment]
Advanced Search will help users a lot. ACCEPTED
