### ISSUE TITLE
AT-3.1: Inventory manager creates stock-keeper account

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#218]
### User Story: ALTA-3.1 (#49)
As an inventory manager, I want to be able to create a stock-keeper’s user account so that I can grant them access to ALTA to perform audits.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Employees_ side menu option.
3. The user is presented with a table displaying the organization's employee accounts and a _Create_ button.
4. The user selects the _Create_ button to display an empty form for the user to input the new stock-keeper's information.
5. Once the form is complete, the user submits the data by clicking the _Save_ button. The user is then redirected back to the table to validate the creation of the user.

**Comment by ajaykaushik17** [comment]
ACCEPTED
