### ISSUE TITLE
AT-3.2: Inventory manager modifies stock-keeper's user information

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#219]
### User Story: ALTA-3.2 (#50)
As an inventory manager, I want to be able to modify a stock-keeper’s user information so that I can correct outdated data.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Employees_ side menu option.
3. The user is presented with a table containing an overview of the affiliated employee user accounts' information.
4. The user selects the _Settings_ button (grey dot) at the end of the respective employee's row.
5. The user is presented with a form containing the employee's account information and selects the _Edit_ button.
6. Once the information is modified, the user selects the _Save_ button to store the updated data. The form is then refreshed to display the updated information.

**Comment by ajaykaushik17** [comment]
ACCEPTED
