### ISSUE TITLE
AT-3.3: Create an audit template

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#220]
### User Story: ALTA-3.3 (#51)
As an inventory manager, I want to be able to create a customizable auditing template so that I can audit items based on specified inventory requirements.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Template_ side menu option.
3. The user is presented with the organization's predefined templates (if any) and an _Add_ button.
4. The user selects the _Add_ button.
5. The user is presented with an empty form containing the template's title, selected fields, and a description text field.
6. The user inputs the template information and selects the _Save_ button. 
7. The user is redirected back to the _Templates_ page to confirm the template creation.

**Comment by ajaykaushik17** [comment]
Audit Template functionality - ACCEPTED
