### ISSUE TITLE
AT-3.4: Modify audit template

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#221]
### User Story: ALTA-3.4 (#52)
As an inventory manager, I want to be able to modify a customizable auditing template so that I can adjust the specified requirements of a potential audit.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Template_ side menu option.
3. The user is presented with the organization's predefined templates.
4. The user selects a template's _three vertical dots_ button and selects the _Edit_ option from the sub-menu.
5. The user is presented with a completed form containing disabled (greyed out) input fields and an _Edit_ button.
6. The user modifies the template information and selects the _Save_ button. The form is then refreshed to display the updated information.

**Comment by ajaykaushik17** [comment]
ACCEPTED.
