### ISSUE TITLE
AT-3.5: Assign stock-keepers to audits

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#222]
### User Story: ALTA-3.5 (#53)
As an inventory manager, I want to be able to assign stock-keepers to perform audits so that I can manage the execution of multiple tasks simultaneously.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user may initiate an audit using 2 methods:

    a. The user selects individual items through the _Inventory Items_ page:
       i. The user selects the _Inventory Items_ side menu option.
       ii. The user is presented with a table containing the organization's inventory items and a column of checkboxes associated with each listed item.
      iii. The user marks the checkboxes of the items to be audited and selects the _Start Audit_ button.

    b. The user selects a template from the _Templates_ page:
        i. The user selects the _Template_ side menu option.
       ii. The user is presented with the organization's predefined templates.
      iii. The user selects the desired audit template to begin the audit process.

3. Once the audit is initiated, the user is redirected to the _Select Stock-Keepers_ page, which lists the availability of each stock-keeper per location and a column of checkboxes associated with each employee.
4. The user marks the checkboxes of the assigned stock-keepers and selects the _Assign_ button.
5. The user is presented with the _Designate Bins to Stock-Keepers_ page, which contains the locations of the selected items in separate expansion cards. Each expansion card presents the list of bins affiliated with the items to be audited as well as the assigned stock-keepers.
6. The user drags and drops the bins to the desired stock-keeper to assign the workload and selects the _Assign_ button.
7. The user is redirected to the _Audit Review_ page to ensure the selected criteria are correct before initiating the audit.

**Comment by ajaykaushik17** [comment]
Process is well executed. ACCEPTED
