### ISSUE TITLE
AT-3.6: Schedule an automatic audit

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#223]
### User Story: ALTA-3.6 (#54)
As an inventory manager, I want to be able to schedule automatic audits at a specified frequency so that I can routinely reinitiate audits.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Template_ side menu option.
3. The user is presented with the organization's predefined templates (if any) and an _Add_ button.
4. The user selects the _Add_ button.
5. The user is presented with an empty form containing the template's input fields and scheduling sub-section.
6. The user inputs the template information and schedules the audit's start date, start time, recurrence, and time zone.
7. The user selects the _Save_ button. 
8. The user is redirected back to the _Templates_ page to confirm the template creation.

**Comment by ajaykaushik17** [comment]
ACCEPTED
Note: need to make sure assignment of stock keepers for scheduled/automatic audits is aligned with their availability.
OR defaulted to some specific stock keepers.
