### ISSUE TITLE
AT-3.9: Automatically assign bins to stock-keepers

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#255]
### User Story: ALTA-3.9 (#193)
As an inventory manager, I want to be able to automatically assign bins to stock-keepers so that I can have tasks equally distributed among available employees.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Inventory Items_ side menu option.
3. The user is presented with a table containing the organization's inventory items and a column of checkboxes associated with each listed item.
4. The user marks the checkboxes of the items to be audited and selects the _Start Audit_ button.
5. The user is redirected to the _Select Stock-Keepers_ page and marks the checkboxes of the assigned stock-keepers and selects the _Assign_ button.
6. The user is redirected to the  _Designate Bins to Stock-Keepers_ page which contains the _Auto Assign_ button.
7. The user selects the _Auto Assign_ button which assigns the listed bins to the selected stock-keepers based on Round Robin assignment. The allocation can also be modified by dragging and dropping the associated bins to other stock-keepers' assigned tasks.

**Comment by ajaykaushik17** [comment]
Great time saver for Inventory manager and stock keepers workload mgmt. Accepted
