### ISSUE TITLE
AT-4.2: Review the list of inputted items of an ongoing audit 

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#256]
### User Story: ALTA-4.2 (#57)
As a stock-keeper, I want to be able to review the inputted items of an ongoing audit so that I can determine my progress towards completion.

### Acceptance Criteria
Given that the user is logged into the mobile application as a stock-keeper,

1. The user should be redirected to the _Audits_ page where the list of assigned audits is displayed.
2.  The user selects the _i_ button on the right side of an audit to view a banner containing the progression details of that audit.
3. The user selects any audit to navigate to the audit's _Bins_ page.
4. The user selects the _i_ button on the right side of a bin to view a banner containing the progression details of that specific bin.
5. The user selects any bin to navigate to the bin's _Items_ page.
6. The user confirms the item's presence by selected the _circular blue checkmark_ button.
7. A pop-up appears displaying the item's information and a _Submit_ button. The user selects the _Submit_ button.
8. A second pop-up appears to ensure the user that the item is successfully validated. The user selects the _Dismiss_ button to close the pop-up window.
9. The user selects the _Completed Items_ tab and is presented with the list of inputted items.

**Comment by ajaykaushik17** [comment]
Accepted.
