### ISSUE TITLE
AT-4.3: Input an item’s data using the barcode scanner

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#257]
### User Story: ALTA-4.3 (#58)
As a stock-keeper, I want to be able to input an item’s data using the barcode scanner so that I can automatically submit its information during an audit.

### Acceptance Criteria
Given that the user is logged into the mobile application as a stock-keeper,

1. The user should be redirected to the _Audits_ page where the list of assigned audits is displayed.
2. The user selects any audit to navigate to the audit's _Bins_ page.
3. The user selects any bin to navigate to the bin's _Items_ page.
4. The user scans a barcode that is linked to one of the listed item's data.
5. A pop-up appears displaying the item's information and a _Submit_ button. The user selects the _Submit_ button.
6. A second pop-up appears to ensure the user that the item is successfully validated. The user selects the _Dismiss_ button to close the pop-up window. 
7. The user selects the _Completed Items_ tab and is presented with the list of inputted items.

**Comment by ajaykaushik17** [comment]
Accepted. Very well done.
