### ISSUE TITLE
AT-4.4: Manually input an item’s data

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#258]
### User Story: ALTA-4.4 (#59)
As a stock-keeper, I want to be able to manually input an item’s data so that I can manage its information in case of barcode scanning failure.

### Acceptance Criteria
Given that the user is logged into the mobile application as a stock-keeper,

1. The user should be redirected to the _Audits_ page where the list of assigned audits is displayed.
2. The user selects any audit to navigate to the audit's _Bins_ page.
3. The user selects any bin to navigate to the bin's _Items_ page.
4. The user is presented with the list of items to be audited and two buttons identified as _Camera_ and _Input_. The user selects the _Input_ button.
5. A popup appears requesting the user to input the barcode number. The user selects the input field and uses the mobile's keypad to enter the barcode number. Once completed, the user selects the _Confirm_ button.
6. A second pop-up appears to ensure the user that the item is successfully validated. The user selects the _Dismiss_ button to close the pop-up window.
7. The user selects the _Completed Items_ tab and is presented with the list of inputted items.

**Comment by ajaykaushik17** [comment]
Please make sure if camera is unable to capture the scan, it recommends stockkeeper to enter it manually.
Manual Entry Option is a key backup feature. Accepted (pending above validation)

**Comment by ajaykaushik17** [comment]
Accepted. Useful for damaged barcodes
