### ISSUE TITLE
AT-4.5: Flag an item as missing or new

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#259]
### User Story: ALTA-4.5 (#60)
As a stock-keeper, I want to be able to flag an unexpected item so that I can alert the inventory manager of the discrepancy.

### Acceptance Criteria
Given that the user is logged into the mobile application as a stock-keeper,

1. The user should be redirected to the _Audits_ page where the list of assigned audits is displayed.
2. The user selects any audit to navigate to the audit's _Bins_ page.
3. The user selects any bin to navigate to the bin's _Items_ page.
4. The user is presented with the list of items to be audited and two buttons identified as _Camera_ and _Input_. The user inputs an item's barcode information using any of the three methods (barcode scanner, camera, manual input).
5. The user is able to flag an item in **two ways**

   a) Selecting the _Flag_ button to indicate an item is missing **(missing item)**:
   
      i. The user selects the _Flag_ button of any of the listed items which displays a popup containing the selected item's data, the expected quantity of the item, a comment input field, and a _Flag as Missing_ button.
      
      ii. A second pop-up appears to ensure the user that the item is successfully validated. The user selects the _Dismiss_ button to close the pop-up window.
      
      iii. The user selects the _Completed Items_ tab and is presented with the list of inputted items.

   b) Inputting an item's barcode that is not on the list of items **(new item)**:
   
      i. A pop-up appears stating that there is no match between the inputted data and the list of items. The user is presented with the _Dismiss_ button to cancel the input and the _Add as New_ button to add a new item to the list.
      
      ii. The user selects the _Add as New_ button which displays another popup containing the item's scanned barcode, the discovered quantity, a comment input field, and a _Flag as New_ button.
      
      iii. The user inputs the quantity of discovered items and selects the _Flag as New_ button.
      
      iv. A second pop-up appears to ensure the user that the item is successfully validated. The user selects the _Dismiss_ button to close the pop-up window.
      
      v. The user selects the _Completed Items_ tab and is presented with the list of inputted items.

**Comment by ajaykaushik17** [comment]
It is a very important feature to flag lost and found items. Great job. Accepted
