### ISSUE TITLE
AT-4.6: Comment on a flagged item

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#260]
### User Story: ALTA-4.6 (#61)
As a stock-keeper, I want to be able to comment on a flagged item so that I can provide additional details of its condition to the inventory manager.

### Acceptance Criteria
Given that the user is logged into the mobile application as a stock-keeper,

1. The user should be redirected to the _Audits_ page where the list of assigned audits is displayed.
2. The user selects any audit to navigate to the audit's _Bins_ page.
3. The user selects any bin to navigate to the bin's _Items_ page.
4. The user is presented with the list of items to be audited and two buttons identified as _Camera_ and _Input_. The user selects the _Flag_ button on any of the listed items.
5. The user is presented with a popup containing the selected item's data, the expected quantity of the item, a comment input field, and a _Flag as Missing_ button.
6. The user selects the comment input field and inputs a comment. Once completed, the user selects the _Flag as Missing_ button.
7. A second pop-up appears to ensure the user that the item is successfully validated. The user selects the Dismiss button to close the pop-up window.
8. The user selects the Completed Items tab and is presented with the list of inputted items.

Note: the same general steps apply for commenting on a _New Item_.

**Comment by ajaykaushik17** [comment]
Accepted.
