### ISSUE TITLE
AT-4.7: View items assigned to an audit

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#261]
### User Story: ALTA-4.7 (#70)
As a stock-keeper, I want to be able to view the items that I need to audit so that I can look for them while working.

### Acceptance Criteria
Given that the user is logged into the mobile application as a stock-keeper,

1. The user should be redirected to the _Audits_ page where the list of assigned audits is displayed.
2. The user selects any audit to navigate to the audit's _Bins_ page.
3. The user selects any bin to navigate to the bin's _Items_ page which displays the list of items that need to be audited.

**Comment by ajaykaushik17** [comment]
Very well done. Accepted
