### ISSUE TITLE
AT-4.8: Manage the details of any found item 

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#262]
### User Story: ALTA-4.8 (#131)
As a stock-keeper, I want to be able to manage the details of any found item during an audit, so that I can fix any mistakes I made.

### Acceptance Criteria
Given that the user is logged into the mobile application as a stock-keeper,

1. The user should be redirected to the _Audits_ page where the list of assigned audits is displayed.
2. The user selects any audit to navigate to the audit's _Bins_ page.
3. The user selects any bin to navigate to the bin's _Items_ page.
4. The user is presented with the list of items to be audited and a tab labeled _Completed Items_. The user selects the _Completed Items_ tab.
5. The user is presented with the list of validated items and their corresponding status (provided, missing, new). As well, each item contains a _Settings_ button represented as a gear icon.
6. The user selects the _Settings_ button. A bottom popup appears allowing the user to manage the details of the item with the _Edit_ or _Remove_ buttons. The user can also cancel the operation by selecting the _Cancel_ button.
7. The user selects the _Edit_ button to leave a comment on a found item and selects the _Submit_ button.
8. A second pop-up appears to ensure the user that the record is successfully modified. The user selects the _Dismiss_ button to close the pop-up window.

**Comment by ajaykaushik17** [comment]
This checkpoint will improve the quality of data captured from the field. Accepted.
