### ISSUE TITLE
AT-4.9: Stock-keeper logs into mobile application using a generated pin

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#263]
### User Story: ALTA-4.9 (#132)
As a stock-keeper, I want to be able to log in without a password, so that I don’t have to remember another login credential.

### Acceptance Criteria
Given that the user is a stock-keeper and has an ALTA account with a validated email address,

1. The user launches the mobile application and is presented with the login page to enter their email address.
2. The user submits their email address and selects the _Send Pin_ button. The user is navigated to the following page which accepts the generated pin.
3. The user receives an email with the subject labeled _ALTA Pin_. The user opens the email and enters the given pin in the mobile application's input field.
4. Once completed, the user selects the _Sign In_ page. If the correct pin is submitted, the user is navigated to the _Audits_ page.

**Comment by ajaykaushik17** [comment]
Accepted.
