### ISSUE TITLE
AT-4.1: New Audit Notification

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#269]
### User Story: ALTA-4.1 (#56)
As a stock-keeper, I want to be notified once an audit is assigned to me so that I can perform the audit as soon as possible.

### Acceptance Criteria
Given that the user is logged into the mobile application as a stock-keeper and an inventory manager recently assigned the user to a newly initiated audit,

1. The user should be redirected to the _Audits_ page where the list of assigned audits is displayed. As well, the page should contain a bell that represents notifications. The bell should have a red circle containing a numbered value to determine the total value of newly assigned audits.
2. The user selects the bell to determine which audits were newly assigned. A window appears displaying the newly assigned audits.
3. The user selects the corresponding audit from the _Audits_ list which marks the notification as _seen_ and decreases the value in the red circle by 1.

**Comment by ajaykaushik17** [comment]
Accepted.
