### ISSUE TITLE
AT-5.7: Dashboard of recent audit activity

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#272]
### User Story: ALTA-5.7 (#195)
As an inventory manager, I want to be able to view a dashboard of recent audit activity so that I can review updates in a centralized location.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user is redirected to the _Dashboard_ page which contains an overview of audit data over the past month.

**Comment by ajaykaushik17** [comment]
Accepted
