### ISSUE TITLE
AT-3.10: Cancel an active audit

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#274]
### User Story: ALTA-3.10 (#194)
As an inventory manager, I want to be able to cancel an audit so that I can undo an accidental initiation.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Audits_ side menu option.
3. The user is presented with a table containing the list of ongoing and archived audits.
5. The user selects an ongoing audit and is presented with another table detailing the information of the audit.
6. The user selects the _Cancel_ button which then displays a popup message to confirm the action.
7. The user confirms the cancellation of the audit and deletes it from the database.

### Related Mockups:

- Inventory manager login page
<img width="660" alt="log in" src="https://user-images.githubusercontent.com/35980232/103579566-c9c58680-4ed8-11eb-946e-f837b6382b7d.png">

- Audit page
<img width="695" alt="audit" src="https://user-images.githubusercontent.com/35980232/113350131-0b62a380-9307-11eb-8cba-156f97e93de2.png">

**Comment by ajaykaushik17** [comment]
Accepted.
