### ISSUE TITLE
AT-5.1: View an audit report in a graphical format

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#275]
### User Story: ALTA-5.1 (#62)
As an inventory manager, I want to be able to view an audit report so that I can analyze the discovered discrepancies of a completed audit in a graphical format.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Audits_ side menu option.
3. The user is presented with a table containing the list of ongoing and archived audits.
4. The user selects the _Graphs and Trends_ tab on top of the audits table.
5. The user is presented with an interactive graph to view the overall accuracy trends over a specified period of time.

**Comment by ajaykaushik17** [comment]
It is a good visual feature. Accepted.
