### ISSUE TITLE
AT-5.2: Export audit results in csv file

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#276]
### User Story: ALTA-5.2 (#63)
As an inventory manager, I want to be able to export the inventory data of a performed audit so that I can use it in the company’s ERP system.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Audits_ side menu option.
3. The user is presented with a table containing the list of ongoing and archived audits.
4. The user selects a desired audit and is presented with another table detailing the information of the audit.
5. The user selects the _Export Audit_ button. The CSV file downloads onto the user's device.

**Comment by ajaykaushik17** [comment]
Accepted. Please make sure audited items status is included in extract.

**Comment by Amanda-Kolopa** [comment]
I'm reopening this issue to confirm that the audited items status is included in the results extract

**Comment by ajaykaushik17** [comment]
Accepted.
