### ISSUE TITLE
AT-5.3: Review archived audits

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#277]
### User Story: ALTA-5.3 (#64)
As an inventory manager, I want to be able to review archived audits so that I can analyze the inventory’s accuracy levels for trends.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Audits_ side menu option.
3. The user is presented with a table containing the list of ongoing and archived audits.
4. The user selects the arrow at the end of a recorded audit. A brief drop-down table lists an overview of the select audit's content.
5. The user selects a desired audit and is presented with another table detailing the information of the audit.

**Comment by ajaykaushik17** [comment]
Accepted.
