### ISSUE TITLE
AT-5.5: Audit recommendations and insights

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#278]
### User Story: ALTA-5.5 (#66)
As an inventory manager, I want to be able to view recommendations for applying corrective measures to the company’s ERP system so that I can be advised on which actions to improve the inventory’s accuracy level.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Audits_ side menu option.
3. The user is presented with a table containing the list of ongoing and archived audits.
4. The user selects the _Recommendations_ tab on top of the audits table.
5. The user is presented with a list of recommendations based on their previously completed audits.

**Comment by ajaykaushik17** [comment]
Accepted. Additional Requirement (Optional)- (If possible, please provide option to initiate audit using recommendations)

**Comment by ajaykaushik17** [comment]
Much better process. Accepted.
