### ISSUE TITLE
AT-5.6: Comment on an audit report

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#279]
### User Story: ALTA-5.6 (#67)
As an inventory manager, I want to be able to comment on an audit report so that I can provide additional information for other inventory managers to review.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user should be redirected to the _Dashboard_ page.
2. The user selects the _Audits_ side menu option.
3. The user is presented with a table containing the list of ongoing and archived audits.
4. The user selects a desired audit and is presented with another table detailing the information of the audit.
5. The user selects the _Comment_ button. The right-side menu appears and displays the conversation attached to the audit.

**Comment by ajaykaushik17** [comment]
Accepted.
