### ISSUE TITLE
AT-6.1: Reset account password

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#280]
### User Story: ALTA-6.1 (#198)
As a system administrator or inventory manager, I want to be able to reset my ALTA account’s password so that I can change it in case I forget it.

### Acceptance Criteria
Given that the user is a system administrator or inventory manager with a previously registered email address to ALTA,

1. The user navigates to the _Login_ page and selects the _Forgot credentials_ link.
2. The user is presented with a dialog box containing an input field for the user's email address. The user enters their valid email address and selects the _Submit_ button
3. The user receives an email containing a link to gain access to ALTA. The user selects the provided link.
4. The user is navigated to their _Profile Settings_ page. The page displays a form containing the user's information.
5. The user updates the _Password_ input field with the new password and selects the _Save_ button.

**Comment by ajaykaushik17** [comment]
Accepted.
