### ISSUE TITLE
AT-3.8: Upload a csv file to link warehouse locations to stock-keepers

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#293]
### User Story: ALTA-3.8 (#192)
As an inventory manager, I want to be able to upload a csv file of my organization’s warehouse locations so that I can link stock-keepers to their place of employment.

### Acceptance Criteria
Given that the user is logged in as an inventory manager,

1. The user selects the _Organization Settings_ side navigation option.
2. The user selects the _Edit_ button to enable the form fields. 
3. The user drags and drops the inventory extract csv file containing the locations of the warehouses. 
4. The user sets the _Repeat Every:_ value to 0 Days and selects the _Save_ button. The system will rely on the locations in the extract to match stock-keepers with their place of employment.

**Comment by ajaykaushik17** [comment]
Accepted.
