### ISSUE TITLE
AT-3.7: Review audit's selection components before initiation

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Fruity-Loops/ALTA#294]
### User Story: ALTA-3.7 (#55)
As an inventory manager, I want to be able to review an audit’s selected components so that I can validate the task before initiating it.

### Acceptance Criteria
Given that the user is logged in as in inventory manager,

1. The user initiates an audit through the _Inventory Items_ page or _Templates_ page.
2. The user selects the stock-keepers to be assigned to the audit and then selects the _Assign_ button.
3. The user designates the bins to the selected stock-keepers and then selects the _Assign_ button.
4. The user is presented with a table describing the selected components of the audit. 
5. Once reviewed and confirmed that the corresponding data is correct, the user selects the _Confirm_ button to initiate the audit.

**Comment by ajaykaushik17** [comment]
Accepted
