### ISSUE TITLE
Inventory Manager Dashboard

### ISSUE THREAD

**Issue by Averynder** [Fruity-Loops/ALTA#5]
As an inventory manager, there are several tasks that need to be accomplished listed as follows:
- create a stock-keeper’s user account
- modify a stock-keeper’s user information
- create a customizable auditing template
- modify manage a customizable auditing template
- assign stock-keepers to perform audits
- schedule automatic audits at a specified frequency
- review a stock-keeper’s assigned audits

Create a dashboard that can be used as the inventory manager to perform the tasks listed above

**Comment by NicholasNagy** [comment]
Closing as this is an implementation specific issue unrelated any specific user story.

More User stories will be open as issues to better represent the specified features
