### ISSUE TITLE
Release Report Requirements

### ISSUE THREAD

**Issue by NicholasNagy** [Fruity-Loops/ALTA#78]
Write up the Requirements for the the release plan.

BacklogAll IDs will have a link to the corresponding user story in ZehHub/GitHub or JIRA. Youcan also group user stories into EPICs in the table below. This table should be consistent with your Backlog in ZenHub or JIRA at any time during the project. To indicate that a user story has been deleted you can use strikethrough. To indicate a change in the user story points strikethrough the old value and add the new value next to it. Newly added user stories will be highlighted in green color font.

**Comment by Amanda-Kolopa** [comment]
### Expected delivery date:

- set up tables and links: November 4 to 5
- update required content: November 7
